### PR TITLE
Feature: Powerups

### PR DESCRIPTION
**Pull request by amrit-choudhary**
Powerups added to the game
Currently 5 types of powerups are in the game. Go over a powerup to pick it up. Currently active powerups are shown in top left of the screen.

- Double Damage: Doubles the damge caused to bricks
double_damage

- Double Power: Sriker's power is doubled
double_power

- Double Score: Score is doubled
double_score

- Double Speed: Ball's maximum speed is doubled
double_speed

- No Friction: Friction is removed temporarily
no_friction

### CODE REVIEW

**Comment by thealphadollar** [comment]
Before anything, I'd like them to be added to the readme.

**Comment by amrit-choudhary** [comment]
Okay

**Review by thealphadollar — CHANGES_REQUESTED** [review]
I would like you to test this thoroughly before I can test and approve it. This is a great PR but it has the potential of having a lot of bugs due to it's complexity.

**Comment by thealphadollar** [comment]
In what ways do you think will it be beneficial to have that for our game?

**Comment by thealphadollar** [comment]
@amrit-choudhary Please respond.

**Comment by amrit-choudhary** [comment]
I'm not working on it anymore.

**Comment by amrit-choudhary** [comment]
The powerup part was complete, 3d thing was a separate thing and won't affect the main game.

**Comment by thealphadollar** [comment]
Thank you for the PR.

**Pull request merged**
