### PR TITLE
Joystick support and Error handling in case of error with relative imports 

### PR DESCRIPTION
**Pull request by prashantramnani**

### CODE REVIEW

**Comment by thealphadollar** [comment]
@prashantramnani It'll take me some time to test this, please work on other issues in the meantime.

P.S. Please resolve the merge conflict.

**Comment by prashantramnani** [comment]
Any reviews?

**Comment by thealphadollar** [comment]
I already gave one 3 days ago.

> The joystick changes looks great to me, thanks a lot @prashantramnani

> I would request you to update the README.md accordingly and also add the joystick with which the changes have been tested in the README.md

**Comment by thealphadollar** [comment]
ping @prashantramnani

**Comment by thealphadollar** [comment]
@prashantramnani Please resolve the conflict.

**Comment by prashantramnani** [comment]
Done, please review @thealphadollar

**Comment by prashantramnani** [comment]
I have no clue where that file came from, but I'll remove it

**Comment by amrit-choudhary** [comment]
@prashantramnani Hi, I have created an input package which handles the keyboard inputs. It's easier to use than the default pygame system. Do you want to work together and add joystick support for that?
My package can be found here:
https://github.com/vineetjc/pygame-Coin-Fall-/tree/master/src/input_package

**Comment by prashantramnani** [comment]
Yeah sure @amrit-choudhary

**Pull request merged**
