### PR TITLE
added joystick control

### PR DESCRIPTION
**Pull request by prashantramnani**
Joystick support was added using the basic pygame functions. It is only working for one of the controllers I have. The other controller wasn't working in any pygame which support joystick motion. Probably the pygame module supports standard gamepads. And for the joystick to work its has to be plugged in before launching the game.

### CODE REVIEW

**Comment by thealphadollar** [comment]
Have you tested this?

**Comment by prashantramnani** [comment]
Yes it was working for me. Is it not working?

**Comment by thealphadollar** [comment]
I meant to ask how did you test the code you added?

**Comment by prashantramnani** [comment]
By playing the game with the joystick. Is there any other way to test it?

**Pull request closed without merging**
